# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.29

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/saszombie/Coding/sdmProj

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/saszombie/Coding/sdmProj

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/saszombie/Coding/sdmProj/CMakeFiles /home/saszombie/Coding/sdmProj//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/saszombie/Coding/sdmProj/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.s
.PHONY : main.cpp.s

source/Doctor.o: source/Doctor.cpp.o
.PHONY : source/Doctor.o

# target to build an object file
source/Doctor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/source/Doctor.cpp.o
.PHONY : source/Doctor.cpp.o

source/Doctor.i: source/Doctor.cpp.i
.PHONY : source/Doctor.i

# target to preprocess a source file
source/Doctor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/source/Doctor.cpp.i
.PHONY : source/Doctor.cpp.i

source/Doctor.s: source/Doctor.cpp.s
.PHONY : source/Doctor.s

# target to generate assembly for a file
source/Doctor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/source/Doctor.cpp.s
.PHONY : source/Doctor.cpp.s

source/HealthServicies.o: source/HealthServicies.cpp.o
.PHONY : source/HealthServicies.o

# target to build an object file
source/HealthServicies.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/source/HealthServicies.cpp.o
.PHONY : source/HealthServicies.cpp.o

source/HealthServicies.i: source/HealthServicies.cpp.i
.PHONY : source/HealthServicies.i

# target to preprocess a source file
source/HealthServicies.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/source/HealthServicies.cpp.i
.PHONY : source/HealthServicies.cpp.i

source/HealthServicies.s: source/HealthServicies.cpp.s
.PHONY : source/HealthServicies.s

# target to generate assembly for a file
source/HealthServicies.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/source/HealthServicies.cpp.s
.PHONY : source/HealthServicies.cpp.s

source/MainSystem.o: source/MainSystem.cpp.o
.PHONY : source/MainSystem.o

# target to build an object file
source/MainSystem.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/source/MainSystem.cpp.o
.PHONY : source/MainSystem.cpp.o

source/MainSystem.i: source/MainSystem.cpp.i
.PHONY : source/MainSystem.i

# target to preprocess a source file
source/MainSystem.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/source/MainSystem.cpp.i
.PHONY : source/MainSystem.cpp.i

source/MainSystem.s: source/MainSystem.cpp.s
.PHONY : source/MainSystem.s

# target to generate assembly for a file
source/MainSystem.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/source/MainSystem.cpp.s
.PHONY : source/MainSystem.cpp.s

source/MedicalEncounter.o: source/MedicalEncounter.cpp.o
.PHONY : source/MedicalEncounter.o

# target to build an object file
source/MedicalEncounter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/source/MedicalEncounter.cpp.o
.PHONY : source/MedicalEncounter.cpp.o

source/MedicalEncounter.i: source/MedicalEncounter.cpp.i
.PHONY : source/MedicalEncounter.i

# target to preprocess a source file
source/MedicalEncounter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/source/MedicalEncounter.cpp.i
.PHONY : source/MedicalEncounter.cpp.i

source/MedicalEncounter.s: source/MedicalEncounter.cpp.s
.PHONY : source/MedicalEncounter.s

# target to generate assembly for a file
source/MedicalEncounter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/source/MedicalEncounter.cpp.s
.PHONY : source/MedicalEncounter.cpp.s

source/Patient.o: source/Patient.cpp.o
.PHONY : source/Patient.o

# target to build an object file
source/Patient.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/source/Patient.cpp.o
.PHONY : source/Patient.cpp.o

source/Patient.i: source/Patient.cpp.i
.PHONY : source/Patient.i

# target to preprocess a source file
source/Patient.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/source/Patient.cpp.i
.PHONY : source/Patient.cpp.i

source/Patient.s: source/Patient.cpp.s
.PHONY : source/Patient.s

# target to generate assembly for a file
source/Patient.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/source/Patient.cpp.s
.PHONY : source/Patient.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... main"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... source/Doctor.o"
	@echo "... source/Doctor.i"
	@echo "... source/Doctor.s"
	@echo "... source/HealthServicies.o"
	@echo "... source/HealthServicies.i"
	@echo "... source/HealthServicies.s"
	@echo "... source/MainSystem.o"
	@echo "... source/MainSystem.i"
	@echo "... source/MainSystem.s"
	@echo "... source/MedicalEncounter.o"
	@echo "... source/MedicalEncounter.i"
	@echo "... source/MedicalEncounter.s"
	@echo "... source/Patient.o"
	@echo "... source/Patient.i"
	@echo "... source/Patient.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

